//
//  SessionDetailView.swift
//  heatlab
//
//  Detailed view for a single session
//

import SwiftUI
import SwiftData
import HealthKit

struct SessionDetailView: View {
    @Environment(\.modelContext) var modelContext
    @Environment(\.dismiss) var dismiss
    @Environment(UserSettings.self) var settings
    @Environment(SubscriptionManager.self) var subscriptionManager
    let session: SessionWithStats
    let baselineEngine: BaselineEngine

    @State private var isGeneratingSummary = false
    @State private var localAiSummary: String?
    @State private var isEditing = false
    @State private var showingDeleteConfirmation = false
    @State private var showingDiscardConfirmation = false
    @State private var showingPaywall = false
    @State private var heartRateDataPoints: [HeartRateDataPoint] = []
    @State private var allHeartRateDataPoints: [HeartRateDataPoint] = []
    @State private var isLoadingHeartRate = false
    @State private var hasAutoGeneratedInsight = false
    
    // Edit state
    @State private var editedDuration: TimeInterval = 0
    @State private var maxDuration: TimeInterval = 0
    @State private var editedIsHeated: Bool = true
    @State private var editedTemperature: Int = 95
    @State private var editedSessionTypeId: UUID?
    @State private var editedNotes: String = ""
    @State private var editedPerceivedEffort: PerceivedEffort = .none
    @State private var hapticGenerator: UIImpactFeedbackGenerator?
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                if isEditing {
                    editModeContent
                } else {
                    viewModeContent
                }
            }
            .padding()
        }
        .background(Color.hlBackground)
        .navigationTitle(isEditing ? "Edit Session" : "Session Details")
        .navigationBarTitleDisplayMode(.inline)
        .navigationBarBackButtonHidden(isEditing)
        .toolbar {
            if isEditing {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button {
                        if hasUnsavedChanges {
                            showingDiscardConfirmation = true
                        } else {
                            cancelEditing()
                        }
                    } label: {
                        Image(systemName: "chevron.left")
                    }
                }
            }
            ToolbarItem(placement: .navigationBarTrailing) {
                if isEditing {
                    Button("Save") {
                        saveChanges()
                    }
                } else {
                    Button("Edit") {
                        startEditing()
                    }
                }
            }
        }
        .onAppear {
            // Update baselines when viewing session
            baselineEngine.updateBaseline(for: session.session, averageHR: session.stats.averageHR)
            baselineEngine.updateSessionTypeBaseline(for: session.session, averageHR: session.stats.averageHR)

            // Load heart rate data
            Task {
                await loadHeartRateData()
            }

            // Auto-generate AI insight for Pro users on first view (if no cached summary)
            if subscriptionManager.isPro
                && session.session.aiSummary == nil
                && localAiSummary == nil
                && !hasAutoGeneratedInsight
                && SummaryGenerator.isAvailable {
                hasAutoGeneratedInsight = true
                generateSummary()
            }
        }
        .alert("Unsaved Changes", isPresented: $showingDiscardConfirmation) {
            Button("Save", role: nil) {
                saveChanges()
            }
            Button("Discard", role: .destructive) {
                cancelEditing()
            }
            Button("Cancel", role: .cancel) { }
        } message: {
            Text("You have unsaved changes. Would you like to save or discard them?")
        }
        .alert("Delete Session", isPresented: $showingDeleteConfirmation) {
            Button("Cancel", role: .cancel) { }
            Button("Delete", role: .destructive) {
                deleteSession()
            }
        } message: {
            Text("Are you sure you want to delete this session? This action cannot be undone.")
        }
    }
    
    @ViewBuilder
    private var viewModeContent: some View {
        VStack(alignment: .leading, spacing: 20) {
            // Header with workout type icon
            HStack(spacing: 12) {
                Image(systemName: settings.sessionType(for: session.session.sessionTypeId)?.icon ?? SFSymbol.yoga)
                    .font(.title)
                    .foregroundStyle(Color.hlAccent)

                VStack(alignment: .leading, spacing: 4) {
                    Text(settings.sessionTypeName(for: session.session.sessionTypeId) ?? session.session.workoutTypeDisplayName)
                        .font(.title2.bold())
                    Text(session.session.startDate.formatted(date: .complete, time: .shortened))
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
            }

            // Unified Insight Card (replaces stat grid, baseline comparison, and AI summary)
            SessionInsightCard(
                session: session,
                temperatureComparison: baselineEngine.compareToBaseline(session: session),
                classTypeComparison: baselineEngine.compareToSessionTypeBaseline(session: session),
                isPro: subscriptionManager.isPro,
                aiInsight: localAiSummary ?? session.session.aiSummary,
                isGeneratingInsight: isGeneratingSummary,
                onRefreshTap: { generateSummary() },
                onUpgradeTap: { showingPaywall = true }
            )

            // Heart Rate Chart
            if !heartRateDataPoints.isEmpty {
                HeartRateChartView(
                    dataPoints: heartRateDataPoints,
                    duration: session.session.manualDurationOverride ?? session.stats.duration,
                    minHR: session.stats.minHR > 0 ? session.stats.minHR : 0,
                    maxHR: session.stats.maxHR,
                    averageHR: session.stats.averageHR
                )
            } else if isLoadingHeartRate {
                VStack {
                    ProgressView()
                        .padding()
                    Text("Loading heart rate data...")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .frame(maxWidth: .infinity)
                .frame(height: 220)
                .background(Color.hlSurface)
                .clipShape(RoundedRectangle(cornerRadius: 16))
            }

            // Perceived Effort (always shown)
            VStack(alignment: .leading, spacing: 8) {
                Text("Perceived Effort")
                    .font(.headline)
                Text(session.session.perceivedEffort.displayName)
                    .font(.body)
                    .foregroundStyle(.secondary)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .heatLabSecondaryCard()

            // Notes (always shown)
            VStack(alignment: .leading, spacing: 8) {
                Text("Notes")
                    .font(.headline)
                if let notes = session.session.userNotes, !notes.isEmpty {
                    Text(notes)
                        .font(.body)
                        .foregroundStyle(.secondary)
                } else {
                    Text("No notes")
                        .font(.body)
                        .foregroundStyle(.tertiary)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .heatLabSecondaryCard()

            // Source (only shown when known)
            if session.session.source != .unknown {
                HStack {
                    Text("Source")
                        .font(.headline)
                    Spacer()
                    Text(session.session.source.displayName)
                        .font(.body)
                        .foregroundStyle(.secondary)
                }
                .heatLabSecondaryCard()
            }
        }
        .sheet(isPresented: $showingPaywall) {
            PaywallView()
        }
    }

    @ViewBuilder
    private var editModeContent: some View {
        VStack(alignment: .leading, spacing: 24) {
            // Duration Editor
            if allHeartRateDataPoints.isEmpty {
                DurationTimelineSlider(
                    maxDuration: maxDuration,
                    selectedDuration: $editedDuration
                )
            } else {
                HeartRateTrimChartView(
                    dataPoints: allHeartRateDataPoints,
                    maxDuration: maxDuration,
                    trimDuration: $editedDuration
                )
            }
            
            // Heated Toggle
            Toggle("Heated Session", isOn: $editedIsHeated.animation(.easeInOut(duration: 0.2)))
                .tint(Color.hlAccent)
                .padding()
                .background(
                    RoundedRectangle(cornerRadius: 16)
                        .fill(Color(.systemBackground))
                        .shadow(color: .black.opacity(0.05), radius: 8, x: 0, y: 2)
                )
            
            // Temperature Editor (only shown when heated)
            if editedIsHeated {
                VStack(alignment: .leading, spacing: 8) {
                    Text("Temperature")
                        .font(.headline)

                    HStack(spacing: 0) {
                        Picker("Temperature", selection: $editedTemperature) {
                            ForEach((70...120).reversed(), id: \.self) { temp in
                                Text("\(temp)°").tag(temp)
                            }
                        }
                        .pickerStyle(.wheel)
                        .frame(width: 80, height: 120)
                        .clipped()
                        .onChange(of: editedTemperature) { _, _ in
                            hapticGenerator?.impactOccurred()
                        }

                        Spacer()

                        // Visual temperature indicator
                        VStack(spacing: 12) {
                            Image(systemName: "thermometer.medium")
                                .font(.system(size: 40))
                                .foregroundStyle(temperatureColor(for: editedTemperature))

                            Text("\(editedTemperature)°\(settings.temperatureUnit == .fahrenheit ? "F" : "C")")
                                .font(.system(.title, design: .rounded, weight: .bold))
                                .foregroundStyle(temperatureColor(for: editedTemperature))
                        }
                        .frame(maxWidth: .infinity)
                    }
                    .padding()
                    .background(
                        RoundedRectangle(cornerRadius: 16)
                            .fill(Color(.systemBackground))
                            .shadow(color: .black.opacity(0.05), radius: 8, x: 0, y: 2)
                    )
                }
            }
            
            // Session Type Editor
            VStack(alignment: .leading, spacing: 8) {
                Text("Session Type")
                    .font(.headline)
                SessionTypePillGrid(
                    sessionTypes: settings.manageableSessionTypes,
                    selectedTypeId: $editedSessionTypeId
                )
            }

            // Perceived Effort Editor
            VStack(alignment: .leading, spacing: 8) {
                Text("Perceived Effort")
                    .font(.headline)
                Menu {
                    ForEach(PerceivedEffort.allCases, id: \.self) { effort in
                        Button(effort.displayName) {
                            editedPerceivedEffort = effort
                        }
                    }
                } label: {
                    HStack {
                        Text(editedPerceivedEffort.displayName)
                            .foregroundStyle(.primary)
                        Spacer()
                        Image(systemName: "chevron.up.chevron.down")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    .padding()
                    .background(
                        RoundedRectangle(cornerRadius: 16)
                            .fill(Color(.systemBackground))
                            .shadow(color: .black.opacity(0.05), radius: 8, x: 0, y: 2)
                    )
                }
            }

            // Notes Editor
            VStack(alignment: .leading, spacing: 8) {
                Text("Notes")
                    .font(.headline)
                ZStack(alignment: .topLeading) {
                    if editedNotes.isEmpty {
                        Text("Add notes about this session...")
                            .foregroundStyle(.secondary)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 16)
                    }
                    TextEditor(text: $editedNotes)
                        .frame(minHeight: 120)
                        .scrollContentBackground(.hidden)
                        .padding(8)
                }
                .background(
                    RoundedRectangle(cornerRadius: 16)
                        .fill(Color(.systemBackground))
                        .shadow(color: .black.opacity(0.05), radius: 8, x: 0, y: 2)
                )
            }
            
            // Delete button
            Button(role: .destructive) {
                showingDeleteConfirmation = true
            } label: {
                HStack {
                    Spacer()
                    Image(systemName: SFSymbol.trash)
                    Text("Delete Session")
                    Spacer()
                }
                .padding()
                .background(Color.red.opacity(0.1))
                .foregroundStyle(.red)
                .clipShape(RoundedRectangle(cornerRadius: HeatLabRadius.md))
            }
        }
    }

    private var hasUnsavedChanges: Bool {
        let currentDuration = session.stats.duration
        let currentIsHeated = session.session.roomTemperature != nil
        let currentTemperature = session.session.roomTemperature ?? 95
        let currentSessionTypeId = session.session.sessionTypeId
        let currentNotes = session.session.userNotes ?? ""
        let currentEffort = session.session.perceivedEffort

        if editedDuration != currentDuration { return true }
        if editedIsHeated != currentIsHeated { return true }
        if editedIsHeated && editedTemperature != currentTemperature { return true }
        if editedSessionTypeId != currentSessionTypeId { return true }
        if editedNotes != currentNotes { return true }
        if editedPerceivedEffort != currentEffort { return true }
        return false
    }

    private func cancelEditing() {
        isEditing = false
        hapticGenerator = nil
    }

    private func startEditing() {
        // Initialize edit state from session
        // Use original workout duration as max (before any manual override)
        if let workout = session.workout, workout.duration > 0 {
            maxDuration = workout.duration
        } else if let endDate = session.session.endDate {
            maxDuration = endDate.timeIntervalSince(session.session.startDate)
        } else {
            // Fallback to current duration if no workout/endDate
            maxDuration = session.stats.duration
        }

        // Start with overridden duration if set, otherwise full duration
        if let override = session.session.manualDurationOverride {
            editedDuration = override
        } else {
            editedDuration = session.stats.duration
        }

        // Heated is determined by presence of temperature
        editedIsHeated = session.session.roomTemperature != nil
        editedTemperature = session.session.roomTemperature ?? 95
        editedSessionTypeId = session.session.sessionTypeId
        editedNotes = session.session.userNotes ?? ""
        editedPerceivedEffort = session.session.perceivedEffort

        // Prepare haptic generator for temperature picker
        hapticGenerator = UIImpactFeedbackGenerator(style: .light)
        hapticGenerator?.prepare()

        isEditing = true
    }
    
    private func saveChanges() {
        session.session.markUpdated()

        // Update duration - only set override if significantly different from max (within 1 second tolerance)
        let tolerance: TimeInterval = 1.0
        if editedDuration > tolerance && abs(editedDuration - maxDuration) > tolerance {
            session.session.manualDurationOverride = editedDuration
        } else {
            // Reset to original duration
            session.session.manualDurationOverride = nil
        }

        // Update temperature (nil means unheated)
        session.session.roomTemperature = editedIsHeated ? editedTemperature : nil
        
        // Update other fields
        session.session.sessionTypeId = editedSessionTypeId
        session.session.userNotes = editedNotes.isEmpty ? nil : editedNotes
        session.session.perceivedEffort = editedPerceivedEffort

        try? modelContext.save()
        isEditing = false

        // Clean up haptic generator
        hapticGenerator = nil

        // Reload heart rate data to reflect duration changes
        Task {
            await loadHeartRateData()
        }
    }
    
    private func deleteSession() {
        session.session.softDelete()
        try? modelContext.save()
        dismiss()
    }
    
    private func formatDuration(_ duration: TimeInterval) -> String {
        let hours = Int(duration) / 3600
        let minutes = Int(duration) / 60 % 60
        let seconds = Int(duration) % 60
        
        if hours > 0 {
            return String(format: "%d:%02d:%02d", hours, minutes, seconds)
        } else {
            return String(format: "%d:%02d", minutes, seconds)
        }
    }
    
    private func generateSummary() {
        guard !isGeneratingSummary else { return }

        isGeneratingSummary = true
        let temperatureComparison = baselineEngine.compareToBaseline(session: session)
        let classTypeComparison = baselineEngine.compareToSessionTypeBaseline(session: session)
        let typeName = settings.sessionTypeName(for: session.session.sessionTypeId)
        let temperatureBaselines = baselineEngine.allTemperatureBaselines()
        let classTypeBaselines = baselineEngine.allSessionTypeBaselines()

        Task {
            do {
                let generator = SummaryGenerator()
                let summary = try await generator.generateSummary(
                    for: session,
                    temperatureComparison: temperatureComparison,
                    classTypeComparison: classTypeComparison,
                    sessionTypeName: typeName,
                    temperatureBaselines: temperatureBaselines,
                    classTypeBaselines: classTypeBaselines,
                    temperatureUnit: settings.temperatureUnit
                )

                // Update the session with the summary
                await MainActor.run {
                    session.session.aiSummary = summary
                    localAiSummary = summary
                    try? modelContext.save()
                    isGeneratingSummary = false
                }
            } catch {
                print("Failed to generate summary: \(error)")
                await MainActor.run {
                    isGeneratingSummary = false
                }
            }
        }
    }
    
    private func loadHeartRateData() async {
        await MainActor.run {
            isLoadingHeartRate = true
        }

        do {
            let repository = SessionRepository(modelContext: modelContext)
            let dataPoints = try await repository.fetchHeartRateDataPoints(for: session.session)

            // Store unfiltered points for edit mode trim chart
            await MainActor.run {
                allHeartRateDataPoints = dataPoints
            }

            // Filter heart rate data points based on manual duration override for view mode
            var filteredPoints = dataPoints
            if let manualDuration = session.session.manualDurationOverride {
                filteredPoints = dataPoints.filter { $0.timeOffset <= manualDuration }
            }

            await MainActor.run {
                heartRateDataPoints = filteredPoints
                isLoadingHeartRate = false
            }
        } catch {
            print("Failed to load heart rate data: \(error)")
            await MainActor.run {
                allHeartRateDataPoints = []
                heartRateDataPoints = []
                isLoadingHeartRate = false
            }
        }
    }

    private func temperatureColor(for temp: Int) -> Color {
        Color.HeatLab.temperature(fahrenheit: temp)
    }

    private func temperatureLabel(for temp: Int) -> String {
        switch temp {
        case ..<85: return "Cool"
        case 85..<95: return "Warm"
        case 95..<105: return "Hot"
        default: return "Very Hot"
        }
    }
}

#Preview {
    NavigationStack {
        SessionDetailView(
            session: SessionWithStats(
                session: {
                    let s = WorkoutSession(workoutUUID: UUID(), startDate: Date(), roomTemperature: 102)
                    s.sessionTypeId = SessionTypeConfig.DefaultTypeID.vinyasa
                    s.aiSummary = "Great session! You maintained a strong, consistent effort throughout this vinyasa class. Your heart rate stayed in your typical range for 102°F sessions."
                    return s
                }(),
                workout: nil,
                stats: SessionStats(averageHR: 145, maxHR: 168, minHR: 95, calories: 387, duration: 2732)
            ),
            baselineEngine: BaselineEngine(modelContext: try! ModelContainer(for: WorkoutSession.self).mainContext)
        )
    }
    .environment(UserSettings())
    .environment(SubscriptionManager())
}
